---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: authelia:k3s-users
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: authelia:k3s-users
roleRef:
  kind: ClusterRole
  name: authelia:k3s-users
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: authelia:k3s-users
    apiGroup: rbac.authorization.k8s.io
