apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-1r
parameters:
  dataEngine: v1
  dataLocality: strict-local
  disableRevisionCounter: "true"
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  unmapMarkSnapChainRemoved: ignored
provisioner: driver.longhorn.io
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
