apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-2r
parameters:
  dataEngine: v1
  dataLocality: best-effort
  disableRevisionCounter: "true"
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  unmapMarkSnapChainRemoved: ignored
provisioner: driver.longhorn.io
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
