controller:
  resources:
    requests:
      cpu: 3m
      memory: 256Mi
    limits:
      memory: 256Mi

speaker:
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      memory: 128Mi
  frr:
    resources:
      requests:
        cpu: 2m
        memory: 64Mi
      limits:
        memory: 64Mi
