apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: argocd-image-updater
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 1.0.5
      helm:
        valueFiles:
          - $values/argo-cd/helm_values/k3s-ceplea/argocd-image-updater/values.yaml
    - repoURL: https://github.com/ionutbalutoiu/home-k8s.git
      targetRevision: HEAD
      ref: values
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
