apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-ovh
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: cert-manager-webhook-ovh
      repoURL: https://aureq.github.io/cert-manager-webhook-ovh
      targetRevision: 0.8.0
      helm:
        valueFiles:
          - $values/argo-cd/helm_values/k3s-ceplea/cert-manager-webhook-ovh/values.yaml
    - repoURL: https://github.com/ionutbalutoiu/home-k8s.git
      path: charts/external-secrets
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/argo-cd/helm_values/k3s-ceplea/cert-manager-webhook-ovh/values_external_secrets.yaml
    - repoURL: https://github.com/ionutbalutoiu/home-k8s.git
      targetRevision: HEAD
      ref: values
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
