apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: external-secrets
      repoURL: https://charts.external-secrets.io
      targetRevision: 1.2.0
      helm:
        valueFiles:
          - $values/argo-cd/helm_values/k3s-ceplea/external-secrets/values.yaml
    - repoURL: https://github.com/ionutbalutoiu/home-k8s.git
      path: charts/external-secrets
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/argo-cd/helm_values/k3s-ceplea/external-secrets/values_external_secrets.yaml
    - repoURL: https://github.com/ionutbalutoiu/home-k8s.git
      targetRevision: HEAD
      ref: values
    - path: argo-cd/extras/k3s-ceplea/external-secrets
      repoURL: https://github.com/ionutbalutoiu/home-k8s.git
      targetRevision: HEAD
      directory:
        recurse: true
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
