apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: immich
      repoURL: https://immich-app.github.io/immich-charts
      targetRevision: 0.10.3
      helm:
        valueFiles:
          - $values/argo-cd/helm_values/k3s-ceplea/immich/values.yaml
    - repoURL: https://github.com/ionutbalutoiu/home-k8s.git
      path: charts/external-secrets
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/argo-cd/helm_values/k3s-ceplea/immich/values_external_secrets.yaml
    - repoURL: https://github.com/ionutbalutoiu/home-k8s.git
      targetRevision: HEAD
      ref: values
    - path: argo-cd/extras/k3s-ceplea/immich
      repoURL: https://github.com/ionutbalutoiu/home-k8s.git
      targetRevision: HEAD
      directory:
        recurse: true
  destination:
    namespace: immich
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
