apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip-cloud-provider
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: kube-vip-cloud-provider
      repoURL: https://kube-vip.github.io/helm-charts
      targetRevision: 0.2.10
      helm:
        valueFiles:
          - $values/argo-cd/helm_values/k3s-ceplea/kube-vip-cloud-provider/values.yaml
    - repoURL: https://github.com/ionutbalutoiu/home-k8s.git
      targetRevision: HEAD
      ref: values
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
