apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: renovate
      repoURL: ghcr.io/renovatebot/charts
      targetRevision: 46.41.0
      helm:
        valueFiles:
          - $values/argo-cd/helm_values/k3s-ceplea/renovate/values.yaml
    - repoURL: https://github.com/ionutbalutoiu/home-k8s.git
      path: charts/external-secrets
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/argo-cd/helm_values/k3s-ceplea/renovate/values_external_secrets.yaml
    - repoURL: https://github.com/ionutbalutoiu/home-k8s.git
      targetRevision: HEAD
      ref: values
  destination:
    namespace: renovate
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
