apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: traefik-crds
      repoURL: https://helm.traefik.io/traefik
      targetRevision: 1.18.0
      helm:
        valueFiles:
          - $values/argo-cd/helm_values/k3s-ceplea/traefik-crds/values.yaml
    - repoURL: https://github.com/ionutbalutoiu/home-k8s.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
