apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: www-balutoiu
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: app-template
      repoURL: https://bjw-s-labs.github.io/helm-charts
      targetRevision: 4.6.2
      helm:
        valueFiles:
          - $values/argo-cd/helm_values/k3s-ceplea/www-balutoiu/values.yaml
    - repoURL: https://github.com/ionutbalutoiu/home-k8s.git
      targetRevision: HEAD
      ref: values
    - path: argo-cd/extras/k3s-ceplea/www-balutoiu
      repoURL: https://github.com/ionutbalutoiu/home-k8s.git
      targetRevision: HEAD
      directory:
        recurse: true
  destination:
    namespace: www-balutoiu
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
