resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 2m
    memory: 96Mi

config:
  #sessionTTL: 86400
  # Bypasses: https://github.com/kubernetes-sigs/headlamp/issues/4883
  sessionTTL: null
  oidc:
    usePKCE: true
    secret:
      create: false
    externalSecret:
      enabled: true
      name: headlamp-oidc
      hasScopes: true

httpRoute:
  enabled: true
  parentRefs:
    - name: traefik-gateway
      namespace: traefik-internal
  hostnames:
    - headlamp.internal.balutoiu.com
