resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 2m
    memory: 96Mi

config:
  #sessionTTL: 86400
  # Bypasses: https://github.com/kubernetes-sigs/headlamp/issues/4883
  sessionTTL: null
  oidc:
    usePKCE: true
    secret:
      create: false
    externalSecret:
      enabled: true
      name: headlamp-oidc
      hasScopes: true

ingress:
  enabled: true
  ingressClassName: traefik-internal
  hosts:
    - host: headlamp.internal.balutoiu.com
      paths:
        - path: /
          type: Prefix
