global:
  domain: argo.internal.balutoiu.com
  securityContext:
    fsGroup: 999

controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    rules:
      enabled: true
      spec:
        - alert: ArgoAppMissing
          expr: absent(argocd_app_info)
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: "No reported Argo CD applications."
            description: >-
              ArgoCD has not reported any applications data for the past 15 minutes which
              means that it must be down or not functioning properly.
        - alert: ArgoAppNotSynced
          expr: argocd_app_info{sync_status!="Synced"} != 0
          for: 2h
          labels:
            severity: warning
          annotations:
            summary: "Argo CD application is not synced."
            description: >-
              Argo CD application `{{ $labels.name }}` has sync status as `{{ $labels.sync_status }}`.
        - alert: ArgoAppUnhealthy
          expr: argocd_app_info{health_status!="Healthy"} != 0
          for: 2h
          labels:
            severity: critical
          annotations:
            summary: "Argo CD application is unhealthy."
            description: >-
              Argo CD application `{{ $labels.name }}` has health status as `{{ $labels.health_status }}`.
  resources:
    requests:
      cpu: 120m
      memory: 1280Mi
    limits:
      memory: 1280Mi

redis:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi

applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  ingress:
    enabled: true
    hostname: argo-applicationset.balutoiu.com
    path: /api/webhook
    ingressClassName: traefik-external
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi

server:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  ingress:
    enabled: true
    ingressClassName: traefik-internal
  resources:
    requests:
      cpu: 10m
      memory: 512Mi
    limits:
      memory: 512Mi

dex:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      memory: 256Mi

repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      cpu: 473m
      memory: 1Gi
    limits:
      memory: 1Gi

configs:
  cm:
    dex.config: |
      connectors:
        - type: oidc
          id: authelia
          name: Authelia
          config:
            issuer: https://auth.balutoiu.com
            clientID: argocd
            clientSecret: $dex.authelia.oidc.clientSecret
            insecureEnableGroups: true
            userNameKey: preferred_username
            getUserInfo: true
            scopes:
              - profile
              - email
              - groups
  rbac:
    scopes: "[email, groups]"
    policy.default: role:authenticated
    policy.csv: |
      g, k3s-admins, role:admin
      p, role:evelio-project-catalog, projects, get, evelio, allow
      p, role:evelio-project-catalog, projects, get, evelio-dev, allow
      p, role:evelio-project-catalog, projects, get, evelio-staging, allow
      g, evelio, role:evelio-project-catalog
  params:
    server.insecure: true
    controller.sync.timeout.seconds: 300 # 5 minutes
  secret:
    createSecret: false # We manage it with external secrets

notifications:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  argocdUrl: https://argo.internal.balutoiu.com
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi
