apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: home-backup-longhorn-runner
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - persistentvolumeclaims
    verbs:
      - get
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: home-backup-longhorn-runner
subjects:
  - kind: ServiceAccount
    name: backup-cronjobs
    namespace: backup-cronjobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: home-backup-longhorn-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: home-backup-longhorn-snapshots
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots
      - volumesnapshotcontents
    verbs:
      - get
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: home-backup-longhorn-snapshots
subjects:
  - kind: ServiceAccount
    name: backup-cronjobs
    namespace: backup-cronjobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: home-backup-longhorn-snapshots
