global:
  domain: argo.internal.buc.balutoiu.com
  securityContext:
    fsGroup: 999

controller:
  resources:
    requests:
      cpu: 48m
      memory: 680Mi
    limits:
      memory: 680Mi

redis:
  resources:
    requests:
      cpu: 7m
      memory: 32Mi
    limits:
      memory: 32Mi

applicationSet:
  ingress:
    enabled: true
    hostname: argo-applicationset.balutoiu.com
    path: /api/webhook
    ingressClassName: traefik-external
  resources:
    requests:
      cpu: 1m
      memory: 48Mi
    limits:
      memory: 48Mi

server:
  ingress:
    enabled: true
    ingressClassName: traefik-internal
  resources:
    requests:
      cpu: 2m
      memory: 95Mi
    limits:
      memory: 95Mi

dex:
  enabled: false

repoServer:
  resources:
    requests:
      cpu: 8m
      memory: 533Mi
    limits:
      memory: 533Mi

configs:
  params:
    server.insecure: true
    controller.sync.timeout.seconds: 300 # 5 minutes
  secret:
    createSecret: false # We manage it with external secrets

notifications:
  argocdUrl: https://argo.internal.buc.balutoiu.com
  resources:
    requests:
      cpu: 1m
      memory: 48Mi
    limits:
      memory: 48Mi
