resources:
  requests:
    cpu: 3m
    memory: 192Mi
  limits:
    memory: 192Mi

webhook:
  resources:
    requests:
      cpu: 3m
      memory: 128Mi
    limits:
      memory: 128Mi

certController:
  resources:
    requests:
      cpu: 3m
      memory: 256Mi
    limits:
      memory: 256Mi
