global:
  alwaysAppendIdentifierToResourceName: true

controllers:
  backup-hyper-ryzen:
    forceRename: backup-hyper-ryzen
    type: cronjob
    cronjob:
      timeZone: Etc/GMT+2 # Bucharest Timezone
      schedule: "0 14 * * 6" # Every Saturday at 14:00
      backoffLimit: 0
      successfulJobsHistory: 7
      failedJobsHistory: 3
    initContainers:
      copy-rclone-conf:
        image:
          repository: busybox
          pullPolicy: IfNotPresent
          tag: 1.38.0
        command:
          - cp
        args:
          - /secrets/rclone.conf
          - /root/.config/rclone/rclone.conf
    containers:
      home-backup:
        image:
          repository: ghcr.io/ionutbalutoiu/home-backup
          pullPolicy: IfNotPresent
          tag: 2.0.0
        command:
          - home-backup
        args:
          - -log-level
          - debug
          - -config
          - /configs/$(NODE_NAME).yaml
        env:
          RESTIC_HOST: backup-cronjobs
          RESTIC_PASSWORD_FILE: /secrets/restic-password
          NODE_NAME:
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        securityContext:
          privileged: true
    pod:
      automountServiceAccountToken: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - hyper-ryzen

configMaps:
  backup-configs:
    forceRename: backup-configs
    data:
      hyper-ryzen.yaml: |-
        backups:
          ###
          ### Backup LV - pvc-shared
          ###
          - source:
              type: lvm
              vg_name: storage-ssd-nvme-raid0
              lv_name: pvc-shared
            destination:
              type: restic
              repo: rclone:onedrive-iony:restic-backups/k3s-ceplea/hyper-ryzen_lv_pvc-shared
              keep_last: 4
          ###
          ### Backup LV - home
          ###
          - source:
              type: lvm
              vg_name: ubuntu-vg
              lv_name: home
            destination:
              type: restic
              repo: rclone:onedrive-iony:restic-backups/k3s-ceplea/hyper-ryzen_lv_home
              keep_last: 4
          ###
          ### Backup PVC - www-balutoiu/www-balutoiu-www
          ###
          - source:
              type: longhorn_pvc
              pvc_name: www-balutoiu-www
              namespace: www-balutoiu
              snapshot_class: longhorn
            destination:
              type: restic
              repo: rclone:onedrive-iony:restic-backups/k3s-ceplea/hyper-ryzen_pvc_www-balutoiu-www
              keep_last: 4

rawResources:
  longhorn-runner-role:
    forceRename: home-backup-longhorn-runner
    manifest:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        namespace: backup-cronjobs
      rules:
        - apiGroups:
            - ""
          resources:
            - pods
            - persistentvolumeclaims
          verbs:
            - get
            - create
            - delete
        - apiGroups:
            - ""
          resources:
            - pods/log
          verbs:
            - get
        - apiGroups:
            - batch
          resources:
            - cronjobs
          verbs:
            - get
        - apiGroups:
            - snapshot.storage.k8s.io
          resources:
            - volumesnapshots
          verbs:
            - get
            - create
            - delete
  longhorn-runner-role-binding:
    forceRename: home-backup-longhorn-runner
    manifest:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        namespace: backup-cronjobs
      subjects:
        - kind: ServiceAccount
          name: backup-cronjobs
          namespace: backup-cronjobs
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: home-backup-longhorn-runner
  longhorn-source-role:
    forceRename: home-backup-longhorn-source
    manifest:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        namespace: www-balutoiu
      rules:
        - apiGroups:
            - ""
          resources:
            - persistentvolumeclaims
          verbs:
            - get
        - apiGroups:
            - snapshot.storage.k8s.io
          resources:
            - volumesnapshots
          verbs:
            - get
            - create
            - delete
  longhorn-source-role-binding:
    forceRename: home-backup-longhorn-source
    manifest:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        namespace: www-balutoiu
      subjects:
        - kind: ServiceAccount
          name: backup-cronjobs
          namespace: backup-cronjobs
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: home-backup-longhorn-source
  longhorn-snapshot-alias-cluster-role:
    forceRename: home-backup-longhorn-snapshot-alias
    manifest:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      rules:
        - apiGroups:
            - snapshot.storage.k8s.io
          resources:
            - volumesnapshotcontents
          verbs:
            - get
            - create
            - delete
  longhorn-snapshot-alias-cluster-role-binding:
    forceRename: home-backup-longhorn-snapshot-alias
    manifest:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      subjects:
        - kind: ServiceAccount
          name: backup-cronjobs
          namespace: backup-cronjobs
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: home-backup-longhorn-snapshot-alias

persistence:
  host-root:
    type: hostPath
    hostPath: /
    hostPathType: Directory
    globalMounts:
      - path: /host-root

  device-dir:
    type: hostPath
    hostPath: /dev
    hostPathType: Directory
    globalMounts:
      - path: /dev

  lib-modules:
    type: hostPath
    hostPath: /lib/modules
    hostPathType: Directory
    globalMounts:
      - path: /lib/modules

  scripts:
    type: configMap
    identifier: backup-configs
    globalMounts:
      - path: /configs

  rclone-conf:
    type: secret
    name: backup-rclone-conf
    defaultMode: 0600
    globalMounts:
      - path: /secrets/rclone.conf
        subPath: rclone.conf

  restic-password:
    type: secret
    name: backup-restic-password
    defaultMode: 0600
    globalMounts:
      - path: /secrets/restic-password
        subPath: restic-password

  rclone-conf-dir:
    type: emptyDir
    globalMounts:
      - path: /root/.config/rclone
