apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-1password-connect
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: connect
      repoURL: https://1password.github.io/connect-helm-charts
      targetRevision: 2.2.1
      helm:
        valueFiles:
          - $values/argo-cd/helm_values/k3s-buc/external-secrets-1password-connect/values.yaml
    - repoURL: https://github.com/ionutbalutoiu/home-k8s.git
      path: charts/external-secrets
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/argo-cd/helm_values/k3s-buc/external-secrets-1password-connect/values_external_secrets.yaml
    - repoURL: https://github.com/ionutbalutoiu/home-k8s.git
      targetRevision: HEAD
      ref: values
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
