apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-lvm-localpv
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: lvm-localpv
      repoURL: https://openebs.github.io/lvm-localpv
      targetRevision: 1.8.0
      helm:
        valueFiles:
          - $values/argo-cd/helm_values/k3s-buc/openebs-lvm-localpv/values.yaml
    - repoURL: https://github.com/ionutbalutoiu/home-k8s.git
      targetRevision: HEAD
      ref: values
    - path: argo-cd/extras/k3s-buc/openebs-lvm-localpv
      repoURL: https://github.com/ionutbalutoiu/home-k8s.git
      targetRevision: HEAD
      directory:
        recurse: true
  destination:
    namespace: openebs-lvm-localpv
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
