provider:
  name: cloudflare
policy: sync
interval: 1m
sources:
  - service
  - crd

registry: txt
txtOwnerId: k3s-ceplea
txtPrefix: k3s-ceplea-
domainFilters:
  - balutoiu.com

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: external-dns-cloudflare-api-token
        key: CF_API_TOKEN

extraArgs:
  - --txt-wildcard-replacement=asterisk

resources:
  requests:
    cpu: 2m
    memory: 132Mi
  limits:
    memory: 132Mi
