apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool
spec:
  addresses:
    - 10.130.11.10-10.130.11.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ip-pool-l2-adv
spec:
  ipAddressPools:
    - ip-pool
