apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: www-balutoiu-alerts
  labels:
    loki: "1"
spec:
  groups:
    - name: files-browser-frontend-alerts
      rules:
        - alert: FilesBrowserFrontend404Requests
          expr: |
            count_over_time(
                {service_name="www-balutoiu", container="files-browser-frontend"}
                | pattern `<_> - - <_> "<method> <_> <_>" <status> <_> <_> "<_>" <_>`
                | status = "404"
            [5m]) > 200
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: High number of 404 errors in www-balutoiu Files Browser Frontend
            description: |-
              Files Browser Frontend is experiencing a high number of 404 errors. Current count: `{{ $value }}`.
