deployment:
  kind: Deployment
  replicas: 1
  annotations:
    reloader.stakater.com/auto: "true"

service:
  annotations:
    metallb.io/loadBalancerIPs: 10.130.11.100
  spec:
    type: LoadBalancer
    externalTrafficPolicy: Local

accessLog:
  enabled: true
  format: json
  fields:
    headers:
      names:
        User-Agent: keep
        Referer: keep
        X-Forwarded-For: keep
        X-Real-Ip: keep
    queryParameters:
      defaultMode: drop

ports:
  traefiksecure:
    port: 9443
    expose:
      default: true
    http:
      tls:
        enabled: true
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    asDefault: true

ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik-external

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
    allowCrossNamespace: true
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    ingressClass: traefik-external
  file:
    enabled: true
    watch: false
    content:
      tls:
        stores:
          default:
            defaultCertificate:
              certFile: /certs/wildcard-buc-balutoiu-com/tls.crt
              keyFile: /certs/wildcard-buc-balutoiu-com/tls.key

volumes:
  - name: le-wildcard-buc-balutoiu-com-tls
    mountPath: "/certs/wildcard-buc-balutoiu-com"
    type: secret

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.buc.balutoiu.com`)
    entryPoints:
      - "traefiksecure"
    middlewares:
      - name: dashboard-ip-allowlist

resources:
  requests:
    cpu: 5m
    memory: 96Mi
  limits:
    memory: 96Mi

metrics:
  prometheus:
    addRoutersLabels: true
    service:
      enabled: true
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
      rules:
        - alert: TraefikServiceDown
          expr: max by (exported_service) (traefik_service_server_up{namespace="traefik-external"}) == 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: "Traefik service down."
            description: >-
              Traefik service down: `{{ $labels.exported_service }}`.

        - alert: TraefikHighHttp4xxErrorRateService
          expr: |
            (
              sum by (exported_service) (
                rate(traefik_service_requests_total{namespace="traefik-external",code=~"4.*",code!="499"}[3m])
              )
              /
              sum by (exported_service) (
                rate(traefik_service_requests_total{namespace="traefik-external"}[3m])
              )
              * 100
            ) > 25
            and
            (
              sum by (exported_service) (
                increase(traefik_service_requests_total{namespace="traefik-external"}[3m])
              ) > 300
            )
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Traefik high HTTP 4xx error rate service."
            description: >-
              Traefik service 4xx error rate is above 25% for service `{{ $labels.exported_service }}`. Current value is `{{ printf "%.2f" $value }}%`.

        - alert: TraefikHighHttp499RateService
          expr: |
            (
              sum by (exported_service) (
                rate(traefik_service_requests_total{namespace="traefik-external",code="499"}[3m])
              )
              /
              sum by (exported_service) (
                rate(traefik_service_requests_total{namespace="traefik-external"}[3m])
              )
              * 100
            ) > 25
            and
            (
              sum by (exported_service) (
                increase(traefik_service_requests_total{namespace="traefik-external"}[3m])
              ) > 300
            )
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Traefik high HTTP 499 client-abort rate service."
            description: >-
              Traefik service 499 client-abort rate is above 25% for service `{{ $labels.exported_service }}`. Current value is `{{ printf "%.2f" $value }}%`.

        - alert: TraefikHighHttp5xxErrorRateService
          expr: |
            (
              sum by (exported_service) (
                rate(traefik_service_requests_total{namespace="traefik-external",code=~"5.*"}[3m])
              )
              /
              sum by (exported_service) (
                rate(traefik_service_requests_total{namespace="traefik-external"}[3m])
              )
              * 100
            ) > 5
            and
            (
              sum by (exported_service) (
                increase(traefik_service_requests_total{namespace="traefik-external"}[3m])
              ) > 100
            )
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Traefik high HTTP 5xx error rate service."
            description: >-
              Traefik service 5xx error rate is above 5% for service `{{ $labels.exported_service }}`. Current value is `{{ printf "%.2f" $value }}%`.
