---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
spec:
  storageClassName: openebs-lvm-pv-thin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1024Gi
